name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub (if needed)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Docker image (if deploying to DockerHub)
        run: |
          cd backend
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

      - name: Build and Push Frontend Docker image (if deploying to DockerHub)
        run: |
          cd frontend
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
