name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./backend
            image_name: backend
          - context: ./frontend
            image_name: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub (if needed)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Docker image (if deploying to DockerHub)
        run: |
          cd ${{ matrix.context }}
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/project"

      - name: Deploy using Docker Compose on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project
            docker-compose down
            docker-compose pull
            docker-compose up -d
